#!/usr/bin/env python
# Gentoo cleaning script
import subprocess, shutil, os, sys

# Nice colored logs
def paint(color, text, bold=1):
    return f"\033[{0+bold};{color+30};40m\033[49m{text}\033[0m"


def info(text, func=print, func_args={}):
    return func(f"[{paint(2, '*')}] {text}", **func_args)


def warning(text, func=print, func_args={}):
    return func(f"[{paint(3, '!')}] {text}", **func_args)


def error(text, func=print, func_args={}):
    return func(f"[{paint(1, 'x')}] {paint(1, 'error')}: {text}", **func_args)


class Cleaner:
    def __init__(self):
        self.size = 0
        self.force = False
        self.hidden = False
        for arg in sys.argv:
            if arg in ("-f", "--force"):
                self.force = True
            elif arg in ("-dh", "--delete-hidden"):
                self.hidden = True
            elif arg in ("-h", "--help"):
                print("gentoo-clean")
                print("    -f, --force - do not ask")
                print("    -dh, --delete-hidden - delete hidden files")
                print("    -h, --help - print this text")
                exit(0)

    # Main clean function
    def clean(self, folderpath, files, infotext):
        if files != []:
            if not self.force:
                if warning(f"Clean {folderpath}? (y/n): ", func=input).lower() != "y":
                    return
                info(f"{infotext} from {folderpath}")
                for file in files:
                    filepath = os.path.join(folderpath, file)

                    # Hidden files check
                    if not self.hidden:
                        if file.startswith("."):
                            continue

                    try:
                        if os.path.isfile(filepath):
                            size = os.path.getsize(filepath)
                            os.remove(filepath)
                        elif os.path.isdir(filepath):
                            size = self.getFolderSize(filepath)
                            shutil.rmtree(filepath, ignore_errors=True)
                        print(f"    > {filepath} ({self.getSize(size=size)})")
                        self.size += size
                    except PermissionError as p:
                        error(f"{p}")
                        exit(1)
        else:
            info(f"{folderpath} is clean!")

    # Get cleaned size
    def getSize(self, size=None):
        if size == None:
            total = round(self.size / 1024 / 1024, 2)
        else:
            total = round(size / 1024 / 1024, 2)
        return f"{total} MB"

    # Get old kernel files
    @staticmethod
    def getOldKernelFiles(folderpath, smartcheck=True):
        # Get current kernel name
        current_kernel = (
            subprocess.check_output(["uname", "-r"]).decode().split("\n")[0]
        )
        oldkernels = []
        # Find old kernel files
        for file in os.listdir(folderpath):

            # Smart check
            if smartcheck:
                if not any(
                    [
                        i in file
                        for i in ("config-", "initramfs-", "vmlinuz-", "System.map-")
                    ]
                ):
                    continue

            if current_kernel not in file:
                path = os.path.join(folderpath, file)
                oldkernels.append(path)
        return oldkernels

    # Get folder size
    @staticmethod
    def getFolderSize(folder):
        size = 0
        for path, dirs, files in os.walk(folder):
            for f in files:
                fp = os.path.realpath(os.path.join(path, f))
                if os.path.exists(fp):
                    size += os.path.getsize(fp)
        return size


if __name__ == "__main__":
    # System checks

    # Check if system is Gentoo Linux
    isGentoo = False
    if sys.platform == "linux":
        if os.path.exists("/etc/os-release"):
            lines = open("/etc/os-release").read().split("\n")
            for line in lines:
                if line:
                    try:
                        line = line.split("=")
                        if line[0] == "NAME" and line[1] == "Gentoo":
                            isGentoo = True
                    except:
                        pass
    if not isGentoo:
        error("This script is only for Gentoo Linux")
        exit(1)

    # Root user check
    if os.geteuid() != 0:
        error("Run this as root")
        exit(1)

    # Cleaner init
    cleaner = Cleaner()

    # /boot
    boot_files = cleaner.getOldKernelFiles("/boot")
    cleaner.clean("/boot", boot_files, "Cleaning old kernels")

    # /usr/src
    src_kernel_folders = cleaner.getOldKernelFiles("/usr/src", smartcheck=False)
    for xfile in [".keep", "linux"]:
        for file in src_kernel_folders:
            if xfile == os.path.basename(file):
                src_kernel_folders.remove(file)
                break
    cleaner.clean("/usr/src", src_kernel_folders, "Cleaning old kernel src folders")

    # /var/tmp/portage
    portage_tmp = os.listdir("/var/tmp/portage")
    cleaner.clean("/var/tmp/portage", portage_tmp, "Cleaning portage cache")

    # /var/tmp/genkernel
    genkernel_tmp = os.listdir("/var/tmp/genkernel")
    cleaner.clean("/var/tmp/genkernel", genkernel_tmp, "Cleaning genkernel cache")

    # /lib/modules
    lib_modules = cleaner.getOldKernelFiles("/lib/modules", smartcheck=False)
    cleaner.clean("/lib/modules", lib_modules, "Cleaning old kernel modules")

    # /var/cache/distfiles
    distfiles = os.listdir("/var/cache/distfiles")
    cleaner.clean("/var/cache/distfiles", distfiles, "Cleaning portage packages src")

    if cleaner.size != 0:
        info(f"Total cleared size: {cleaner.getSize()}")
